language: c

addons:
    apt:
        packages:
            - elfutils
            - zlib1g-dev
            - gcc-mingw-w64-i686
            - binutils-mingw-w64-i686

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

matrix:
    include:
        - os: linux
          compiler: gcc
          env: HOST="--host=i686-w64-mingw32" TEST="test/main.exe"
    include:
        - os: linux
          compiler: clang
          env: CFLAGS="-fsanitize=address -g" ASAN_OPTIONS="detect_leaks=0"

    exclude:
        - os: osx
          compiler: gcc

script:
    - ./autogen.sh
    - ./configure $HOST
    - make
    - make ${TEST:-test}
